### ISSUE TITLE
Authorization header not present in request object

### ISSUE THREAD

**Issue by myfailemtions** [nuxt-community/strapi-module#9]
### Version
@nuxtjs/strapi: 
v0.1.1

nuxt: 
ex: v2.13.0

### Steps to reproduce

- Install @nuxt/strapi
- On Strapi side create a user with a specific role
- Login with this.$strapi.login() method
- Try to update something that allowed for this role
- Check the request in dev tools
- 403 error response
- Authorization header not present in request object 

### What is Expected?

- Install @nuxt/strapi
- On Strapi side create a user with a specific role
- Login with this.$strapi.login() method
- Try to update something that allowed for this role
- 200 response 
- Authorization header present in the request object 

### What is actually happening?
For some reason, when updating an object in Strapi with a protected route, the authorization header not present in the request object. I can fix it manually set the header before the request.

**Comment by benjamincanac** [comment]
Hey @myfailemtions,

Could you provide the version you're using?

Make sure to use @nuxtjs/strapi v0.1.1 at least.

**Comment by myfailemtions** [comment]
Sorry, forgot to uncomment version, yes it v0.1.1

**Comment by mkalayci35** [comment]
+1 The same happens to me.

**Comment by benjamincanac** [comment]
@myfailemtions Could you provide a reproduction link? Thanks!

**Comment by andyatflocc** [comment]
Hi, I'm having a similar issue i believe:

When I first login using `$strapi.login()` if i do a find, using something like:

`await this.$strapi.find('users')`

it works - the jwt token is passed in the request. If I click the browser refresh button however, it is then not.

as a temporary measure I've added in the second line below in strapi.js
```
this.$http = ctx.$http.create({})
this.$http.setToken(this.getToken (), 'Bearer')
```

**Comment by myfailemtions** [comment]
I fixed with set Token manually, need to provide repo. Will do this soon

**Comment by nkmnz** [comment]
I have the opposite problem from @andyatflocc , a hard reload results in a request with correct authorization header, navigating to a page that uses fetch() to get additional data fails to send the auth header. However, his fix works for me as well, it's in plugin.js:

> ```
> this.$http = ctx.$http.create({})
> this.$http.setToken(this.getToken (), 'Bearer')
> ```

**Comment by Flosciante** [comment]
Hello, 

this problem can appear because the route user/me must have permission in the authenticated role in Strapi. 

As you can see in Plugin.js : 

> try {
      &nbsp;&nbsp;const user = await this.findOne('users', 'me')
      &nbsp;&nbsp;this.setUser(user)
    } catch (e) {
      &nbsp;&nbsp;this.clearToken()
 }

So if the user does have permission, the cookie with token is deleted and a 403 error appears. 

You can solve this problem in the Strapi admin console : 

![image](https://user-images.githubusercontent.com/6696789/89737300-26c72880-da70-11ea-92cc-858186fdc21d.png)

**Comment by nkmnz** [comment]
This might be a possile pitfall as well, but I don't think your comment applies to my problem, @Flosciante . The permission on /users/me was set correctly for the role and `clearToken()` was not called before the 403 (even the cookie is still present).
